name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: make install-uv

    - name: Install dependencies
      run: make setup

    - name: Install dev
      run: make install-dev

    - name: Run release check and build
      run: make release-check
