name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  upload-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: make install-uv

      - name: Install dependencies
        run: make setup

      - name: Install dev
        run: make install-dev

      - name: Run release check and build
        run: make release-check

      - name: Upload Python Package
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
