name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  check-and-build:
    uses: ./.github/workflows/check-build.yml

  upload-package:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Upload Python Package
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
